//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anonQuest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseAnswer
    {
        public int ResponseAnswerID { get; set; }
        public int ResponseID { get; set; }
        public int QuestionID { get; set; }
        public int SelectedAnswer { get; set; }
        public string AnswerText { get; set; }
    }
}
