//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anonQuest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySubject
    {
        public int SubjectID { get; set; }
        public int SurveyID { get; set; }
        public int SeqNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
