//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonQuest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        public int QuestionID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int SeqNo { get; set; }
        public string QuestionText { get; set; }
        public string AnswerType { get; set; }
    }
}
