//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiMarketing.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phi_SurveyResponse
    {
        public int ResponseID { get; set; }
        public int SurveyID { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIp { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public bool Completed { get; set; }
    }
}
